### ISSUE TITLE
Fauna adapter yields "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by BasixKOR** [nextauthjs/adapters#145]
I bascially followed the guide and got this error.

```
.\node_modules\@next-auth\fauna-adapter\src\index.js:1
import { query as q } from "faunadb"
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1021:15)
    at Module._compile (node:internal/modules/cjs/loader:1055:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.@next-auth/fauna-adapter (.\.next\server\pages\api\auth\[...nextauth].js:51:18)
    at __webpack_require__ (.\.next\server\webpack-runtime.js:25:42)
```

**Comment by balazsorban44** [comment]
Make sure you are using the `canary` channel.

Your version should be `0.0.1-canary.155`

**Comment by BasixKOR** [comment]
![image](https://user-images.githubusercontent.com/7413880/123519322-fb562800-d699-11eb-9fea-471b34be46f8.png)
Maybe check again?

**Comment by balazsorban44** [comment]
did you do `npm i @next-auth/fauna-adapter@canary` (or yarn) to install?

**Comment by McTschecker** [comment]
Hi,
I do get that as well with the canary channel. I used ` yarn add @next-auth/fauna-adapter@canary`

**Comment by BasixKOR** [comment]
Yep I did the same too.

**Comment by balazsorban44** [comment]
I identified the problem. We actually don't have a build step for Fauna. We are going to fix this, hopefully in the next couple of days.

cc @ndom91 could you have a look? Either do a js build (eg.: https://github.com/nextauthjs/adapters/blob/main/packages/typeorm-legacy/package.json) or do a "mild" TS conversion and use tsc (see any adapters written in TS)

**Comment by ndom91** [comment]
Hey @BasixKOR, can you give `@next-auth/fauna-adapter@0.1.1-pr.147.3` a try? We released a new version which addresses this. Thank!

**Comment by nles** [comment]
I'm in the process of implementing next-auth with Fauna and noticed this issue as well. Going with `@next-auth/fauna-adapter@0.1.1-pr.147.3` didn't work either. I had to manually create the build in the node_modules directory with Babel to get it to work.

Bit unrelated but it also seems that the documentation is outdated (at https://next-auth.js.org/adapters/fauna). Index called `verification_request_by_token` seems to have been renamed to `verification_request_by_token_and_identifier` at some point.

**Comment by bring-shrubbery** [comment]
@ndom91 This is still happening for me on `@next-auth/fauna-adapter@0.1.1-pr.147.3` as well as on `latest` and `canary`

**Comment by ndom91** [comment]
@nles @bring-shrubbery can you guys give `@next-auth/fauna-adapter@0.1.1-pr.155-677ab725.8` a try? Thanks!

**Comment by bring-shrubbery** [comment]
@ndom91 Now it throws following error:

```
TypeError: (0 , _next_auth_fauna_adapter__WEBPACK_IMPORTED_MODULE_4__.FaunaAdapter) is not a function
```

I'm using Next.js with Typescript btw.

**Comment by ndom91** [comment]
Okay think I got it squared away haha. Please give `@next-auth/fauna-adapter@0.1.1-pr.155-d691430e.8` a shot :+1:

**Comment by bring-shrubbery** [comment]
@ndom91 Works for me now. Thanks! Had to run the schema creation commands from the guide, which I'm not sure if I should have done manually. What do you think?

**Comment by ndom91** [comment]
Great to hear! I'm not sure on that part, personally not super familiar with fauna itself. Maybe @pbteja1998 can chime in?

**Comment by leerob** [comment]
Has a release been cut with the latest fixes? It seems like the docs have been updated as mentioned above 👍

**Comment by pbteja1998** [comment]
@leerob yes, the documentation is updated.

@bring-shrubbery Check out https://github.com/fauna-labs/fauna-schema-migrate if you want to automate this.
You can find the resources at https://github.com/nextauthjs/adapters/tree/main/packages/fauna/tests. You will know what I mean by resources, after you go through the `fauna-schema-migrate` repo.
